Languages =["Pythion","JavaScript","Kotlin","Angular"]
print(Languages)
print(Languages[0])
print(len(Languages))
print(Languages[-1])
Languages.append("React")
print(Languages)
print(Languages[0:2])
print("Angular" in Languages)
Languages.insert(2,"Css")
Languages.remove("Kotlin")
print(Languages)
Languages1=Languages.copy()
print(Languages)